### ISSUE TITLE
热更新时会编译所有东西

### ISSUE THREAD

**Issue by eightHundreds** [zvzuola/react-scaffold#1]
我最后生成的bundle大概8mb,在每次热更新时都会编译出一个8mb的文件

![image](https://user-images.githubusercontent.com/18695431/39125525-cd10c7ca-4731-11e8-89bb-2ce78c17455a.png)

如图,热更新确实生效了,生成了hot-update.json

**Comment by zvzuola** [comment]
这个文件就是你项目的主入口文件啊，只不过在dev环境下所有的内容都打包到这一个文件了，所以比较大，生产环境下打包出的文件会小很多

**Comment by eightHundreds** [comment]
这太慢了

**Comment by zvzuola** [comment]
你可以像生产环境一样把vendor和manifest拿出来，这样会快很多
